name: health_club
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+7

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.2
  auto_route: 10.0.0
  get_it: ^9.0.5
  injectable: ^2.6.0
  alice: ^1.0.0
  alice_dio: ^1.0.7
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.2
  cached_network_svg_image: ^1.2.0
  cached_network_image: ^3.4.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_rating: ^2.0.2
  dropdown_button2: ^2.3.9
  mobile_scanner: ^7.1.3
  yandex_mapkit: 4.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  dotted_border: ^3.1.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  flash: ^3.1.1
  table_calendar: ^3.2.0
  fl_chart: 1.0.0
  syncfusion_flutter_charts: ^31.1.19
  geolocator: ^14.0.2
  hive_ce: ^2.18.0
  path_provider: ^2.1.5
  time_range_picker: ^2.3.1
  activity_ring: ^0.3.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: 10.0.0
  build_runner: 2.5.0
  injectable_generator: ^2.7.0
  json_serializable: 6.9.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
